### ISSUE TITLE
HTTP 500 and no style or images.

### ISSUE THREAD

**Issue by ghost** [Riveu/GamezServer#2]
I get this error if i go to the webpage
[09/May/2014:14:23:37] HTTP
Request Headers:
  AUTHORIZATION: Basic YWRtaW46QEAxMTFtdw==
  COOKIE: plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0
  HOST: 10.0.0.104:5000
  CONNECTION: keep-alive
  Remote-Addr: 10.0.0.119
  ACCEPT: _/_
  USER-AGENT: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36
  ACCEPT-LANGUAGE: nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4
  ACCEPT-ENCODING: gzip,deflate,sdch
[09/May/2014:14:23:37] HTTP Traceback (most recent call last):
  File "/var/gamez/cherrypy/_cprequest.py", line 653, in respond
    self.hooks.run('before_handler')
  File "/var/gamez/cherrypy/_cprequest.py", line 112, in run
    raise exc
ValueError: Static dir requires an absolute dir (or root).

Any idea on how to solve this ?

**Comment by ghost** [comment]
Apparently you have to open it with the full path not with ./GamezServer.py
